# Generated by Django 3.2.10 on 2021-12-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
